app: tooling-s3-sqs
service: tooling-s3-sqs

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-localstack
  - serverless-mocha-plugin
  - serverless-offline

custom:
  serverless-offline:
    useChildProcess: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
